### PR TITLE
Metadata polling settings

### PR DESCRIPTION
**Pull request by reyesml**
For issue #44 

I tested using: OSX 10.10, Sublime Text Build 3083

### CODE REVIEW

**Comment by xjsender** [comment]
@reyesml , can you change the ``metadataPollingFrequency`` name to ``metadata_polling_frequency``, I think we'd better keep the consistent for all settings.

**Comment by reyesml** [comment]
@xjsender , I changed  `metadataPollingFrequency` name to `metadata_polling_frequency`.  Let me know if you need any other changes.

**Comment by xjsender** [comment]
@reyesml , thanks for your understanding, I will merge it right now.

**Comment by xjsender** [comment]
@reyesml , you should add this ``metadata_polling_frequency`` setting into [settings](https://github.com/xjsender/haoide/blob/master/config/settings/toolingapi.sublime-settings) file but not just add it into ``context.py``, if you create new pull request in the next time, you should be aware that.

I have added it for us, you don't need to make change on this pull request, thanks.

**Comment by reyesml** [comment]
@xjsender , sorry for the mistake.  Thanks for adding it.

**Pull request merged**
